import React from 'react';
import Head from 'next/head'
import AboutIndex from '../src/views/About/AboutIndex';


const about = () => {
    return (
        <div>
            <Head>
                <title>About | IYF</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AboutIndex/>
        </div>
    );
};

export default about;