import React from 'react';
import Head from 'next/head';

const blog = () => {
    return (
        <div>
             <Head>
                <title>News | IYF</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head> 
        </div>
    );
};

export default blog;