import React from 'react';
import Head from 'next/head';
import IndexCareer from '../src/views/Career/IndexCareer';

const career = () => {
    return (
        <div>
             <Head>
                <title>Career | IYF</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <IndexCareer/>
        </div>
    );
};

export default career;