import React from 'react';
import Head from 'next/head';
import IndexContact from '../src/views/Contact/IndexContact';

const contact = () => {
    return (
        <div>
            <Head>
                <title>Contact | IYF</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <IndexContact/>
        </div>
    );
};

export default contact;