/* eslint-disable @next/next/no-page-custom-font */
import IndexView from '../src/views/Home/IndexView';
import Head from 'next/head';



export default function Home() {
  return (
    <div>
      <Head>
        <title>HOME | IYF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* components goes here */}
      <IndexView />

    </div>
  )
}
