/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head';
import IndexView from '../src/views/Home/IndexView';

export default function Home() {
  return (
    <div>
      <Head>
        <title>HOME | IYF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
          crossOrigin="anonymous"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Condiment&family=Poppins:ital,wght@0,300;0,400;0,600;1,600&display=swap"
          rel="stylesheet"
        />
        <link href="https://fonts.googleapis.com/css2?family=MonteCarlo&display=swap" rel="stylesheet" />

      </Head>

      <IndexView />
    </div>
  )
}
