import React from 'react';
import Head from 'next/head'
import IndexSponsor from '../src/views/Sponsor/IndexSponsor';

const sponsor = () => {
    return (
        <div>
            <Head>
                <title>Sponsor | IYF</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <IndexSponsor/>
        </div>
    );
};

export default sponsor;