/* eslint-disable @next/next/no-page-custom-font */

import * as React from 'react';
import Box from '@mui/material/Box';
import Drawer from '@mui/material/Drawer';
import CssBaseline from '@mui/material/CssBaseline';
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import List from '@mui/material/List';
import Typography from '@mui/material/Typography';
import Divider from '@mui/material/Divider';
import ListItem from '@mui/material/ListItem';
import ListItemIcon from '@mui/material/ListItemIcon';
import logo from '../assets/images/ignite_youth_foundation_logo.png';
import Image from 'next/Image';
import Avatar from '@mui/material/Avatar';
import { SubjectOutlined, AddCircleOutlineOutlined } from '@mui/icons-material';
import { useRouter } from 'next/router'
import { SSRProvider } from '@react-aria/ssr';

import Head from 'next/head';

const drawerWidth = 240;


export default function LayoutDash({ children }) {
    const router = useRouter()

    const menuItems = [
        {
            text: 'Home',
            icon: <SubjectOutlined color="secondary" />,
            path: '/dashboard'
        },
        {
            text: 'Edit Home Contents',
            icon: <AddCircleOutlineOutlined color="secondary" />,
            path: '/dashboard/home'
        },
       
      
    ];


    return (
        <>
            <Head>
                <title>Dashboard | IYF</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
                    integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
                    crossOrigin="anonymous"
                />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Condiment&family=Poppins:ital,wght@0,300;0,400;0,600;1,600&display=swap"
                    rel="stylesheet"

                />
                <link href="https://fonts.googleapis.com/css2?family=MonteCarlo&display=swap" rel="stylesheet" />
                <script async src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                    crossOrigin="anonymous"></script>
                <script async src="js/jquery-1.11.0.min.js"></script>
                <script async src="js/bootstrap.min.js"></script>
                <script async src="js/wow.min.js"></script>

                <script async src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
                <script async src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
            </Head>
            <Box sx={{ display: 'flex' }}>
                <CssBaseline />

                <AppBar
                    position="fixed"
                    sx={{
                        width: `calc(100% - ${drawerWidth}px)`,
                        ml: `${drawerWidth}px`,
                        backgroundColor: '#000',
                    }}
                    className='dashboard-container'
                >
                    <Toolbar>
                        <Typography variant="h1" noWrap component="div"
                            sx={{
                                fontFamily: 'heading',
                                fontWeight: 'bold',
                                fontSize: '1.5rem !important',
                                cursor: 'pointer',
                                color: '#000 !important',
                                flexGrow: 1,
                            }}
                            className='headings'
                        >
                            Ignite Youth <span className='style-font'
                                style={{
                                    fontSize: '2rem !important',
                                }}
                            >Foundation</span> Dashboard
                        </Typography>

                        <Avatar
                            src='https://raw.githubusercontent.com/iamshaunjp/material-ui-tut/lesson-17/public/mario-av.png'
                            sx={{
                                cursor: "pointer"
                            }}
                        />
                    </Toolbar>
                </AppBar>


                <div
                    className='drawer-main'
                >
                    <Drawer
                        sx={{
                            width: drawerWidth,
                            flexShrink: 0,
                            '& .MuiDrawer-paper': {
                                width: drawerWidth,
                                boxSizing: 'border-box',
                                background: 'none',
                            },
                        }}
                        variant="permanent"
                        anchor="left"
                    >
                        <div
                            style={{
                                width: '130px',
                                position: 'relative',
                                top: '25px',
                                left: '40px',
                                cursor: 'pointer',

                            }}
                        >
                            <Image
                                src={logo}
                                alt="logo"
                            />
                        </div>
                        <Toolbar
                            title="Title"
                        />

                        <Divider />

                        <List>
                            {
                                menuItems.map(item => {
                                    return (
                                        <ListItem button
                                            key={item.text}
                                            onClick={() => router.push(item.path)}
                                            className={router.asPath === item.path ? 'active-dashboard-menu' : ''}
                                        >
                                            <ListItemIcon>{item.icon}</ListItemIcon>
                                            <h2>{item?.text}</h2>
                                        </ListItem>
                                    )
                                })
                            }

                        </List>

                    </Drawer>
                </div>

                <Box
                    component="main"
                    sx={{ flexGrow: 1, bgcolor: 'background.default', p: 3 }}
                >
                    <Toolbar />
                    <div>
                        <SSRProvider>
                            {children}
                        </SSRProvider>
                    </div>
                </Box>
            </Box>
        </>
    );
}
